Info/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.PRINCIPAL , name = 'home'),
    path('Pantalla2/', views.Segunda, name = 'segunda_pantalla'),

    path('Productos/', include('apps.productos.urls'))
]

apps/productos/urls.py
from django.urls import path
from . import views

app_name = 'productos'

urlpatterns = [
    
	path('ALTA_P/', views.Alta_Producto.as_view() , name = 'cargar_p'),
	path('ALTA_R/', views.Alta_Rubro.as_view() , name = 'cargar_r')

]

apps/productos/models.py
from django.db import models

# Create your models here.

class Rubro(models.Model):
	nombre = models.CharField(max_length = 50)

	def __str__(self):
		return self.nombre

class Producto(models.Model):
	nombre = models.CharField(max_length = 50)
	precio = models.IntegerField()
	rubro = models.ForeignKey('Rubro', on_delete = models.CASCADE)
	tamaño = models.IntegerField()
	imagen = models.ImageField(upload_to = 'productos')

	def __str__(self):
		return self.nombre

apps/usuarios/models.py
from django.db import models

from django.contrib.auth. models import AbstractUser

# Create your models here.

class Usuario(AbstractUser):
	nacionalidad = models.CharField(max_length = 30, null = True )
	
	

apps/productos/forms.py
from django import forms
from .models import Producto, Rubro

class Formulario_Alta_Producto(forms.ModelForm):

	class Meta:
		model = Producto
		fields = '__all__'


class Formulario_Alta_Rubro(forms.ModelForm):

	class Meta:
		model = Rubro
		fields = '__all__'

Info/views.py
from django.shortcuts import render


def PRINCIPAL(request):
	return render(request,'home.html')



def Segunda(request):

	return render (request, 'segunda.html')

apps/productos/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .models import Rubro, Producto
from .forms import Formulario_Alta_Producto, Formulario_Alta_Rubro

# Create your views here.

def Listar(request):
	return render(request,'productos/listar.html')

class Alta_Producto(CreateView):
	model = 'Producto'
	form_class = Formulario_Alta_Producto
	template_name = 'productos/alta_producto.html'
	success_url = reverse_lazy('home')

class Alta_Rubro(CreateView):
	model = 'Rubro'
	form_class = Formulario_Alta_Rubro
	template_name = 'productos/alta_rubro.html'
	success_url = reverse_lazy('home')

apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div style='margin:100px;'>  <h5> ENCABEZADO </h5> </div>

	{% block content %}

	{% endblock %}

	<div style='margin:100px;'>  <h5> PIE </h5> </div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}



	{% block content %}

	HOME PANTALLA <br>

	<a href="{% url 'segunda_pantalla' %}">Listar Productos </a>

	<a href="{% url 'productos:cargar_p' %}">Cargar Productos</a><br>
	<a href="{% url 'productos:cargar_r' %}">Cargar Rubro</a><br>

	{% endblock content%}

templates/productos/alta_producto.html
{% extends 'base.html' %}

{% block content %}

	CARGAR UN PRODUCTO
	
	<div style='margin: 50px'>

		<form method='POST'enctype='multipart/form-data'>{% csrf_token %}
			{{form.as_p}}

			<input type="submit" name="Enviar" value="Guardar">		
			
		</form>
			

	</div>

	{% endblock content%}

templates/productos/alta_rubro.html
{% extends 'base.html' %}

{% block content %}

	CARGAR UN RUBRO
	
	<div style='margin: 50px'>

		<form method='POST'enctype='multipart/form-data'>{% csrf_token %}
			{{form.as_p}}

			<input type="submit" name="Enviar" value="Guardar">		
			
		</form>
			

	</div>

	{% endblock content%}

templates/productos/listar.html
{% extends 'base.html' %}



	{% block content %}

	<h3> Listar Productos </h3>

	{% endblock content %}

templates/segunda.html
{% extends 'base.html' %}



	{% block content %}

SOY LA SEGUNDA PANTALLA

<a href="{% url 'home' %}">  'Volver a Home' </a>

	{% endblock content%}